name: cuda
version: "12.3.2"
tier: core
description: "NVIDIA CUDA Toolkit 12.3.2 for GPU-accelerated computing."
abi: linux-gnu-2.34
sources:
  - url: https://developer.download.nvidia.com/compute/cuda/12.3.2/local_installers/cuda_12.3.2_545.23.08_linux.run
    sha256: 24b2afc9f770d8cf43d6fa7adc2ebfd47c4084db01bdda1ce3ce0a4d493ba65b
    file: cuda_installer.run
    arch: x86_64
  - url: https://developer.download.nvidia.com/compute/cuda/12.3.2/local_installers/cuda_12.3.2_545.23.08_linux_sbsa.run
    sha256: 761b84e292b94c4d330f445d36326dfff90a418e909fb0baf3d6f03e24106d08
    file: cuda_installer.run
    arch: arm64
provides:
  - name: cuda
    version: "12.3.2"
  - name: nvcc
    version: "12.3.2"
runtime_requires:
  - name: glibc
    min_version: "2.34"

modulefile_env:
  - var: CUDA_HOME
    path: ""
  - var: CUDA_PATH
    path: ""
