name: python
version: "3.11.11"
tier: core
description: "CPython interpreter version 3.11.11."
abi: linux-gnu-2.34
sources:
  - url: https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tgz
    sha256: 883bddee3c92fcb91cf9c09c5343196953cbb9ced826213545849693970868ed
provides:
  - name: python
    version: "3.11.11"
runtime_requires:
  - name: glibc
    min_version: "2.34"

modulefile_env:
  - var: PYTHON
    path: "bin/python3"
  - var: PYTHONHOME
    path: ""
