package spec

import (
	"fmt"
	"time"
)

// Verification policies recorded in LockFile.VerificationPolicy. They name the
// strongest check the resolver performed on every layer's attestation when it
// produced the lockfile. Resolution holds bundle URIs, not bundle bytes, so it
// never verifies against the transparency log (that happens at strata verify
// --rekor and strata run, where the bytes exist — #85); these two values are
// what a resolve can honestly claim.
const (
	// VerifyAttestationPresent: every layer named a well-formed Sigstore bundle
	// and Rekor entry, checked for presence at resolve time.
	VerifyAttestationPresent = "attestation-present"
	// VerifyUnsignedOffline: at least one layer was accepted with no bundle or
	// Rekor entry, on the offline-catalog path (AllowUnsignedOffline). A lockfile
	// carrying this was not a trust decision.
	VerifyUnsignedOffline = "unsigned-offline"
)

// LockFile is the fully resolved, cryptographically attested description
// of a compute environment. It is machine-generated by the resolver and
// never hand-written.
//
// The LockFile is the reproducibility artifact. It contains:
//   - The SHA256 of the profile that produced it
//   - The exact AMI ID and SHA256 of the base
//   - The SHA256 and Rekor entry for every layer
//   - Its own Rekor entry (the lockfile itself is logged)
//
// A LockFile can be frozen (all versions pinned), published to Zenodo
// (DOI minted), and cited in papers as a verifiable environment reference.
type LockFile struct {
	// Identity
	ProfileName   string    `yaml:"profile" json:"profile"`
	ProfileSHA256 string    `yaml:"profile_sha256" json:"profile_sha256"`
	ResolvedAt    time.Time `yaml:"resolved_at" json:"resolved_at"`
	StrataVersion string    `yaml:"strata_version" json:"strata_version"`

	// Sigstore attestation for the lockfile itself.
	RekorEntry string `yaml:"rekor_entry,omitempty" json:"rekor_entry,omitempty"`
	Bundle     string `yaml:"bundle,omitempty" json:"bundle,omitempty"`

	// VerificationPolicy records what the resolver checked about layer
	// attestations when it produced this lockfile, so a consumer reading only the
	// artifact can interpret its trust status without knowing how it was invoked
	// (#100 / T6). It is one of the Verify* constants below. It is provenance —
	// it records what was checked, not what the environment is — so it does not
	// participate in EnvironmentID (its route is "inert"; nothing at assembly
	// time reads it).
	VerificationPolicy string `yaml:"verification_policy,omitempty" json:"verification_policy,omitempty"`

	// Base is the resolved AMI and its probed capabilities.
	Base ResolvedBase `yaml:"base" json:"base"`

	// Layers are fully resolved, in mount order.
	Layers []ResolvedLayer `yaml:"layers" json:"layers"`

	// Env carries environment variables from the profile for agent configuration.
	Env map[string]string `yaml:"env,omitempty" json:"env,omitempty"`

	// OnReady are commands to run after overlay assembly.
	OnReady []string `yaml:"on_ready,omitempty" json:"on_ready,omitempty"`

	// Defaults lists software modules to pre-load via Lmod at login.
	// Copied from the profile; used by the agent to write strata-defaults.sh.
	Defaults []SoftwareRef `yaml:"defaults,omitempty" json:"defaults,omitempty"`

	// Packages holds the frozen (exactly pinned) package sets resolved from
	// the profile's packages: section. Populated by strata freeze.
	// The agent installs these at boot via pip/conda/cran.
	Packages []ResolvedPackageSet `yaml:"packages,omitempty" json:"packages,omitempty"`

	// MutableLayer records a persistent EBS upper specification copied from
	// the profile. A lockfile with a non-nil MutableLayer is considered
	// "dirty" and cannot be published until strata freeze-layer is called
	// to convert the upper into a signed squashfs layer.
	MutableLayer *MutableLayerSpec `yaml:"mutable_layer,omitempty" json:"mutable_layer,omitempty"`

	// RequiresHost is copied from the profile for reference. Lists ambient
	// host capabilities (GPU driver, EFA, etc.) the environment depends on
	// but that Strata does not install. Advisory only in v0.21.0.
	RequiresHost []HostRequirement `yaml:"requires_host,omitempty" json:"requires_host,omitempty"`
}

// ResolvedBase is the fully resolved base for an environment.
// It records both what the user declared and what was actually resolved.
type ResolvedBase struct {
	// DeclaredOS is the OS string from the profile, e.g. "al2023".
	DeclaredOS string `yaml:"declared_os" json:"declared_os"`

	// AMIID is the resolved EC2 AMI ID, e.g. "ami-0abc123def456789".
	AMIID string `yaml:"ami_id" json:"ami_id"`

	// AMISHA256 is the SHA256 of the base capability *record*
	// (BaseCapabilities.ContentDigest), not of the AMI's filesystem bytes: it
	// digests the probed OS/arch/ABI/compiler/Provides that the resolver actually
	// used, so it is stable across AMI-ID aliasing while committing to nothing
	// about the underlying image bytes (#64). The field is still keyed
	// `ami_sha256` for lockfile compatibility; the name overclaims and is due to
	// become `base_digest` alongside base-digest format validation in #65.
	AMISHA256 string `yaml:"ami_sha256" json:"ami_sha256"`

	// Capabilities is the probed capability set of the base AMI.
	// This is what the resolver used to validate layer requirements.
	Capabilities BaseCapabilities `yaml:"capabilities" json:"capabilities"`
}

// ResolvedLayer is a fully resolved layer in a lockfile.
// It embeds the full LayerManifest plus resolution metadata.
type ResolvedLayer struct {
	LayerManifest `yaml:",inline" json:",inline"`

	// MountOrder is the position in the OverlayFS lower directory stack.
	// Lower numbers are mounted first (closer to the base).
	// The layer with MountOrder=1 is at the bottom of the stack.
	MountOrder int `yaml:"mount_order" json:"mount_order"`

	// SatisfiedBy records which SoftwareRef in the profile this layer
	// was resolved to satisfy. For formation members, this is the
	// formation ref string, e.g. "formation:cuda-python-ml@2024.03".
	SatisfiedBy string `yaml:"satisfied_by" json:"satisfied_by"`

	// FromFormation is the formation name if this layer was expanded
	// from a formation. Empty for standalone refs.
	FromFormation string `yaml:"from_formation,omitempty" json:"from_formation,omitempty"`
}

// IsSigned reports whether the lockfile has been signed and logged to Rekor.
// An unsigned lockfile is a valid intermediate state (pre-signing) but
// should not be used for production launches.
func (l *LockFile) IsSigned() bool {
	return l.RekorEntry != ""
}

// IsFrozen reports whether all layers in the lockfile are pinned by SHA256.
// A frozen lockfile is fully reproducible — no label resolution can
// produce a different result.
func (l *LockFile) IsFrozen() bool {
	for _, layer := range l.Layers {
		if layer.SHA256 == "" {
			return false
		}
	}
	return l.Base.AMISHA256 != ""
}

// LayerCount returns the number of layers in the lockfile.
func (l *LockFile) LayerCount() int {
	return len(l.Layers)
}

// HasMutableLayer reports whether this lockfile references an unfrozen
// mutable EBS upper layer (Path B workflow). Such lockfiles cannot be
// published until strata freeze-layer converts the upper into a signed
// squashfs layer and removes this field.
func (l *LockFile) HasMutableLayer() bool {
	return l.MutableLayer != nil
}

// Validate reports whether the lockfile is well-formed enough to be trusted —
// mounted, published, or used as an identity.
//
// It is a policy check, deliberately separate from ParseLockFileBytes: the parser
// stays able to read a malformed lockfile so a diagnostic such as `strata diff`
// can still inspect one, and the trust boundaries (strata run, publish, freeze)
// call Validate before acting on it. It does not require the lockfile to be
// frozen — an unfrozen lockfile (empty digests) is a valid intermediate state.
// What it forbids is a field that is present but malformed:
//
//   - a non-empty layer SHA256 or Base.AMISHA256 that is not a well-formed digest
//     (#96 — "bbbbbb" and "sha256-ami-test123456789" used to satisfy IsFrozen);
//   - a layer id that is not a safe single path component (#58/#97), since ids
//     become mount points, cache paths, and OCI unpack directories;
//   - two layers sharing a MountOrder, which would leave EnvironmentID dependent
//     on the slice order the mounter falls back to for the tie (#95).
func (l *LockFile) Validate() error {
	seen := make(map[int]bool, len(l.Layers))
	for i, layer := range l.Layers {
		if layer.ID != "" {
			if err := ValidateLayerID(layer.ID); err != nil {
				return fmt.Errorf("lockfile: layer %d: %w", i, err)
			}
		}
		if layer.SHA256 != "" {
			if err := ValidateLayerDigest(layer.SHA256); err != nil {
				return fmt.Errorf("lockfile: layer %d (%s): %w", i, layer.ID, err)
			}
		}
		if seen[layer.MountOrder] {
			return fmt.Errorf("lockfile: two layers share mount_order %d — a mount order must be unique, "+
				"or EnvironmentID depends on the order the layers happen to be written (#95)", layer.MountOrder)
		}
		seen[layer.MountOrder] = true
	}
	if l.Base.AMISHA256 != "" {
		if err := ValidateLayerDigest(l.Base.AMISHA256); err != nil {
			return fmt.Errorf("lockfile: base ami_sha256: %w", err)
		}
	}
	return nil
}

// EnvironmentID returns a stable identifier for this environment. It is the
// SHA256 of a canonical encoding of the lockfile's content; envHashInput in
// lockfile_hash.go is the definition of what that covers, and the rule for
// what may sit outside it is stated there. Do not maintain a second copy of
// the field list here — the one that used to be here drifted twice.
//
// What the identifier commits to:
//
//	Two lockfiles with the same EnvironmentID were assembled from identical
//	instructions. Where those instructions are deterministic — the base image,
//	the layer set and its mount sequence, the exported environment,
//	digest-pinned packages — identical instructions produce identical content.
//	Where they are not — on_ready commands, packages without a digest, a
//	mutable upper — the identity commits to the instruction and not to its
//	outcome.
//
// The second sentence is why this is not "the same ID means the same
// environment": that stronger claim is recorded REFUTED in PROPERTIES.md (X2)
// and the residual is enumerated in docs/environment-identity.md.
//
// Only frozen lockfiles (all SHA256s present) produce a stable ID; a lockfile
// without content hashes returns an empty string, which is not an identity and
// must not be published, tagged or used as a key (#124).
func (l *LockFile) EnvironmentID() string {
	return computeEnvironmentID(l)
}

// ProvenanceRecord returns a human-readable summary of the lockfile's
// attestation chain. Used in paper supplementary materials and
// compliance documentation.
func (l *LockFile) ProvenanceRecord() ProvenanceRecord {
	layers := make([]LayerProvenance, len(l.Layers))
	for i, layer := range l.Layers {
		layers[i] = LayerProvenance{
			Name:       layer.Name,
			Version:    layer.Version,
			SHA256:     layer.SHA256,
			RekorEntry: layer.RekorEntry,
		}
	}
	return ProvenanceRecord{
		Profile:       l.ProfileName,
		ProfileSHA256: l.ProfileSHA256,
		ResolvedAt:    l.ResolvedAt,
		AMIID:         l.Base.AMIID,
		AMISHA256:     l.Base.AMISHA256,
		Layers:        layers,
		LockfileRekor: l.RekorEntry,
		StrataVersion: l.StrataVersion,
	}
}

// ProvenanceRecord is a structured summary of a lockfile's attestation chain.
// Designed for inclusion in supplementary materials and DOI metadata.
type ProvenanceRecord struct {
	Profile       string            `yaml:"profile" json:"profile"`
	ProfileSHA256 string            `yaml:"profile_sha256" json:"profile_sha256"`
	ResolvedAt    time.Time         `yaml:"resolved_at" json:"resolved_at"`
	AMIID         string            `yaml:"ami_id" json:"ami_id"`
	AMISHA256     string            `yaml:"ami_sha256" json:"ami_sha256"`
	Layers        []LayerProvenance `yaml:"layers" json:"layers"`
	LockfileRekor string            `yaml:"lockfile_rekor_entry" json:"lockfile_rekor_entry"`
	StrataVersion string            `yaml:"strata_version" json:"strata_version"`
}

// LayerProvenance is the attestation summary for a single layer.
type LayerProvenance struct {
	Name       string `yaml:"name" json:"name"`
	Version    string `yaml:"version" json:"version"`
	SHA256     string `yaml:"sha256" json:"sha256"`
	RekorEntry string `yaml:"rekor_entry" json:"rekor_entry"`
}
