name: R
version: "4.5.2"
description: "R statistical computing language version 4.5.2."
family: rhel
provides:
  - name: R
    version: "4.5.2"
build_requires:
  - name: gcc
    min_version: "13"
  - name: gfortran
    min_version: "13"
runtime_requires:
  - name: glibc
    min_version: "2.34"
